# Generated by Django 4.0 on 2022-01-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_snip'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snip',
            field=models.CharField(max_length=150),
        ),
    ]
